### ISSUE TITLE
"Alternatives" type question

### ISSUE THREAD

**Issue by thorns-1** [siavashg87/json-joi-converter#17]
Hello!
How do I implement a validation case where a value can be either number or string? In "alternatives" type, when I pass a Schema-like object ({type: "string"}) to the "try" parameter it treats it like I want a value to be equal to this object but not to the schema. So, how this validation can be made? Thanks in advance!

**Comment by vcheeze** [comment]
I just did a quick test on https://npm.runkit.com/json-joi-converter, and it doesn't seem like this is supported right now.

This is what I tried:

```javascript
require("joi/package.json"); // joi is a peer dependency. 
var Joi = require('joi');
var jsonJoiConverter = require("json-joi-converter");

var joi = Joi.object({
  a: Joi.alternatives().try(Joi.number(), Joi.string())
});

console.log(jsonJoiConverter.toJson(joi));
```

And the JSON I got was:

```json
{
    "type": "object",
    "properties": {
        "a": {
            "type": "alternatives"
        }
    }
}
```

Notice that the `try` parameter was not parsed at all.

**Comment by siavashg87** [comment]
Thank you for reporting the issue!

There is now a new version with support for alternatives.

**Comment by thorns-1** [comment]
> I just did a quick test on https://npm.runkit.com/json-joi-converter, and it doesn't seem like this is supported right now.
> 
> This is what I tried:
> 
> ```js
> require("joi/package.json"); // joi is a peer dependency. 
> var Joi = require('joi');
> var jsonJoiConverter = require("json-joi-converter");
> 
> var joi = Joi.object({
>   a: Joi.alternatives().try(Joi.number(), Joi.string())
> });
> 
> console.log(jsonJoiConverter.toJson(joi));
> ```
> 
> And the JSON I got was:
> 
> ```json
> {
>     "type": "object",
>     "properties": {
>         "a": {
>             "type": "alternatives"
>         }
>     }
> }
> ```
> 
> Notice that the `try` parameter was not parsed at all.

Thank you for the investigation into that issue! I didn't think to actually convert the Joi object into JSON

**Comment by thorns-1** [comment]
> Thank you for reporting the issue!
> 
> There is now a new version with support for alternatives.

Thank you for the new version!
