### ISSUE TITLE
Regular expression in joi schema not returned after using toJson and fromJson consequtively.

### ISSUE THREAD

**Issue by meanwesha1** [siavashg87/json-joi-converter#5]
In the following code, i am converting a joi schema to a json object.
const {toJson, fromJson} = require('json-joi-converter')
const newSchema = toJson(
		Joi.object({
			address: Joi.object({
				country: Joi.string(),
				state: Joi.string(),
				city: Joi.string(),
				road: Joi.string(),
				buildingNo: Joi.string()
					.pattern(/^[0-9A-Z/]+$/)
			})
		})
	)

After that, 

console.log( newSchema.properties.address.properties.buildingNo )
o/p: 
{
	type: 'string',
	pattern: { regex: {'$regex': '^[0-9A-Z/]+$'}, options: {} }
}

All good till now. But the problem comes when I am trying to convert this json back to a joi object.

console.log( fromJson(newSchema).describe().keys.address.keys.buildingNo.rules )
o/p:
[ { name:'pattern', args:{ regex: '/[object Object]/' } } ]

Clearly, this should not be the case. It should return the original regular expression. Otherwise I'll not able to use this converted schema to validate my data.
Please take a look.

**Comment by sm-hejazi** [comment]
> In the following code, i am converting a joi schema to a json object.
> const {toJson, fromJson} = require('json-joi-converter')
> const newSchema = toJson(
> Joi.object({
> address: Joi.object({
> country: Joi.string(),
> state: Joi.string(),
> city: Joi.string(),
> road: Joi.string(),
> buildingNo: Joi.string()
> .pattern(/^[0-9A-Z/]+$/)
> })
> })
> )
> 
> After that,
> 
> console.log( newSchema.properties.address.properties.buildingNo )
> o/p:
> {
> type: 'string',
> pattern: { regex: {'$regex': '^[0-9A-Z/]+$'}, options: {} }
> }
> 
> All good till now. But the problem comes when I am trying to convert this json back to a joi object.
> 
> console.log( fromJson(newSchema).describe().keys.address.keys.buildingNo.rules )
> o/p:
> [ { name:'pattern', args:{ regex: '/[object Object]/' } } ]
> 
> Clearly, this should not be the case. It should return the original regular expression. Otherwise I'll not able to use this converted schema to validate my data.
> Please take a look.
I have this issue too
Please take a look.

<div class="js-discussion js-socket-channel ml-0 pl-0 ml-md-6 pl-md-3" data-channel="eyJjIjoibWFya2VkLWFzLXJlYWQ6MTIzODYzODUiLCJ0IjoxNjIxOTU5Nzk2fQ==--f2ad3c00731e4b0ad8485ab54d1534c0fef90f1c6b048a76038ce9063417a4fb" data-channel-target="MDU6SXNzdWU4MTA5NTQxNDk=" style="box-sizing: border-box; margin-left: 40px !important; padding-left: 16px !important; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TimelineItem pt-0 js-comment-container js-socket-channel js-updatable-content" data-gid="MDU6SXNzdWU4MTA5NTQxNDk=" data-url="/_render_node/MDU6SXNzdWU4MTA5NTQxNDk=/issues/body?variables%5BdeferredCommentActions%5D=true" data-channel="eyJjIjoiaXNzdWU6ODEwOTU0MTQ5IiwidCI6MTYyMTk1OTg1MX0=--584c0e7b9e3eaf0494a1e51204146a247ce7e79f5b22c2cb4146c236cc3a435b" style="box-sizing: border-box; padding: 16px 0px; position: relative; display: flex; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issue-810954149" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container js-comment timeline-comment--caret reorderable-task-lists" data-body-version="0c27026d818ef535e54bf563c2ecc98e8adcabff58ab31bfcc8c2a28a6816be3" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border: 1px solid var(--color-border-primary); border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists disabled="" sortable="" style="box-sizing: border-box;">Please take a look.</task-lists><div class="comment-reactions flex-items-center  has-reactions js-reactions-container" style="box-sizing: border-box; align-items: center !important; display: flex; border-top: 1px solid var(--color-border-primary);"><form class="js-pick-reaction" action="https://github.com/siavashg87/json-joi-converter/reactions" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"><div class="comment-reactions-options" style="box-sizing: border-box;"><button class="btn-link reaction-summary-item tooltipped
              tooltipped-se tooltipped-multiline
              user-has-reacted" name="input[content]" type="submit" value="THUMBS_UP unreact" aria-label="sm-hejazi reacted with thumbs up emoji" style="box-sizing: border-box; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit; margin: 0px; overflow: visible; text-transform: none; appearance: none; cursor: pointer; border-radius: 0px 0px 0px 6px; display: inline-block; padding: 9px 15px 7px; color: var(--color-text-link); text-decoration: none; white-space: nowrap; user-select: none; background-color: var(--color-bg-info); border-top: 0px; border-right: 1px solid var(--color-border-primary); border-bottom: 0px; border-left: 0px; border-image: initial; position: relative; float: left;"><g-emoji alias="thumbs up" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png" class="emoji mr-1" style="box-sizing: border-box; font-family: &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 1em; font-weight: 400; line-height: 1; vertical-align: -0.075em; font-style: normal !important; margin-right: 4px !important;">👍</g-emoji><span>&nbsp;</span>1</button><button class="btn-link reaction-summary-item tooltipped
              tooltipped-s tooltipped-multiline
              user-has-reacted" name="input[content]" type="submit" value="CONFUSED unreact" aria-label="sm-hejazi reacted with confused emoji" style="box-sizing: border-box; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit; margin: 0px; overflow: visible; text-transform: none; appearance: none; cursor: pointer; border-radius: 0px; display: inline-block; padding: 9px 15px 7px; color: var(--color-text-link); text-decoration: none; white-space: nowrap; user-select: none; background-color: var(--color-bg-info); border-top: 0px; border-right: 1px solid var(--color-border-primary); border-bottom: 0px; border-left: 0px; border-image: initial; position: relative; float: left;"><g-emoji alias="confused" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f615.png" class="emoji mr-1" style="box-sizing: border-box; font-family: &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 1em; font-weight: 400; line-height: 1; vertical-align: -0.075em; font-style: normal !important; margin-right: 4px !important;">😕</g-emoji><span>&nbsp;</span>1</button></div></form><details class="details-overlay details-reset dropdown hx_dropdown-fullscreen position-relative float-left d-inline-block reaction-popover-container reactions-menu js-reaction-popover-container" style="box-sizing: border-box; display: inline-block !important; position: relative; float: left !important;"><summary class="btn-link reaction-summary-item add-reaction-btn" aria-label="Add your reaction" aria-haspopup="menu" role="button" style="box-sizing: border-box; display: inline-block; cursor: pointer; padding: 9px 15px 7px; font-size: inherit; color: var(--color-text-link); text-decoration: none; white-space: nowrap; user-select: none; background-color: initial; border: 0px; appearance: none; opacity: 0; transition: opacity 0.1s ease-in-out 0s; float: left; line-height: 18px; list-style: none;"><svg aria-hidden="true" viewBox="0 0 16 16" version="1.1" data-view-component="true" height="16" width="16" class="octicon octicon-smiley"><path fill-rule="evenodd" d="M1.5 8a6.5 6.5 0 1113 0 6.5 6.5 0 01-13 0zM8 0a8 8 0 100 16A8 8 0 008 0zM5 8a1 1 0 100-2 1 1 0 000 2zm7-1a1 1 0 11-2 0 1 1 0 012 0zM5.32 9.636a.75.75 0 011.038.175l.007.009c.103.118.22.222.35.31.264.178.683.37 1.285.37.602 0 1.02-.192 1.285-.371.13-.088.247-.192.35-.31l.007-.008a.75.75 0 111.222.87l-.614-.431c.614.43.614.431.613.431v.001l-.001.002-.002.003-.005.007-.014.019a1.984 1.984 0 01-.184.213c-.16.166-.338.316-.53.445-.63.418-1.37.638-2.127.629-.946 0-1.652-.308-2.126-.63a3.32 3.32 0 01-.715-.657l-.014-.02-.005-.006-.002-.003v-.002h-.001l.613-.432-.614.43a.75.75 0 01.183-1.044h.001z"></path></svg></summary></details></div></div></div></div></div><div style="box-sizing: border-box;"><div id="js-timeline-progressive-loader" data-timeline-item-src="siavashg87/json-joi-converter/timeline?id=MDU6SXNzdWU4MTA5NTQxNDk%3D&amp;variables%5Bfirst%5D=60" style="box-sizing: border-box;"></div><div style="box-sizing: border-box;"><div style="box-sizing: border-box;"><div class="js-timeline-marker js-socket-channel js-updatable-content" id="partial-timeline" data-channel="eyJjIjoiaXNzdWU6ODEwOTU0MTQ5IiwidCI6MTYyMTk1OTg1MX0=--584c0e7b9e3eaf0494a1e51204146a247ce7e79f5b22c2cb4146c236cc3a435b" data-url="/_render_node/MDU6SXNzdWU4MTA5NTQxNDk=/issues/unread_timeline?variables%5BdeferCommitBadges%5D=false&amp;variables%5BdeferStatusCheckRollups%5D=false&amp;variables%5BdeferredCommentActions%5D=true&amp;variables%5BhasFocusedReviewComment%5D=false&amp;variables%5BhasFocusedReviewThread%5D=false&amp;variables%5BtimelinePageSize%5D=30&amp;variables%5BtimelineSince%5D=2021-02-18T10%3A13%3A21Z" data-last-modified="Thu, 18 Feb 2021 10:13:21 GMT" data-gid="MDU6SXNzdWU4MTA5NTQxNDk=" style="box-sizing: border-box;"></div></div></div></div></div><span id="issue-comment-box" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></span><span style="color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><div class="discussion-timeline-actions" style="box-sizing: border-box; background-color: var(--color-bg-canvas); border-top: 2px solid var(--color-border-primary); color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="timeline-comment-wrapper timeline-new-comment js-comment-container js-targetable-element  ml-0 pl-0 ml-md-6 pl-md-3" id="issuecomment-new" style="box-sizing: border-box; margin-left: 40px !important; padding-left: 56px; position: relative; margin-top: 16px; margin-bottom: 0px;"><div class=" d-none d-md-block" style="box-sizing: border-box; display: block !important;"><br class="Apple-interchange-newline">

</div></div></div>

**Comment by sm-hejazi** [comment]
I have this issue too
Please take a look.

**Comment by siavashg87** [comment]
Fixed in v 17.2.1-d
